[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/entrypoint.sh"
healthcheckPath = ""
restartPolicyType = "NEVER"
region = "__REGION__"

[deploy.limitOverride.containers]
cpu = __CPU__
memoryBytes = __RAM_BYTES__
